### ISSUE TITLE
fix auth pls

### ISSUE THREAD

**Issue by d1ret** [techchrism/insomnia-plugin-valorant#1]
can't auth with plugin :(

**Comment by techchrism** [comment]
Did this get resolved? I didn't realize until now that the recent cookie reauth changes would likely affect this repo.

**Comment by d1ret** [comment]
yep, i fixed it. 
i added &nonce=1 at the end
const signInUrl = 'https://auth.riotgames.com/authorize?redirect_uri=https%3A%2F%2Fplayvalorant.com%2Fopt_in&client_id=play-valorant-web-prod&response_type=token%20id_token'&nonce=1;
