### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Taimoor-Tariq** [techchrism/insomnia-plugin-valorant#4]
Every time I try to login I get this error
![image](https://user-images.githubusercontent.com/45585081/174085001-94ccfa07-b92b-4d2e-8452-2fd9b23561c2.png)

**Comment by techchrism** [comment]
Are you using the latest version of the plugin? Go to Application->Preferences->Plugins and ensure the plugin is version 1.1.0. If it's not, try uninstalling and reinstalling it.

**Comment by Taimoor-Tariq** [comment]
worked, I had an older version
Thank you
