### ISSUE TITLE
Login screen does not open

### ISSUE THREAD

**Issue by Dreamtrailtv** [techchrism/insomnia-plugin-valorant#7]
I wanted to use the plugin but when I press sign in nothing happens and the console says the following:
![image](https://github.com/techchrism/insomnia-plugin-valorant/assets/51512219/dc485a7f-168b-498a-9d8b-e1fff684b820)
Should I use the latest source because the Insomnia Plugin store does not have the latest commits available?

**Comment by techchrism** [comment]
Sorry, I fixed the issue in the repo but I forgot to publish the changes to npm. The updated version should be available now.
